Repository apoclyps/reviews, pull requests merged in 2021-05, with the labels that each got.

#72 [NO-TICKET] updates README
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#73 [NO-TICKET] Adds publish workflow to push package to PyPi on release
  .github/workflows/publish.yml
  .github/workflows/test.yml
  README.md
Labels: enhancement, github_actions, python

#78 [FEATURE-70] Adds functionality to perform a single render via `--no-reload`
  cli.py
  reviews/layout/helpers.py
  reviews/layout/managers.py
  reviews/tasks.py
Labels: enhancement, python

#88 [NO-TICKET] Enhance project metadata
  .github/FUNDING.yml
  Makefile
  README.md
  reviews/config.py
  reviews/notifications/client.py
  setup.py
  tests/notifications/domain/test_pull_request_notification.py
  tests/notifications/test_client.py
  tests/test_config.py
Labels: documentation, enhancement, python

#89 [NO-TICKET] Improve contextual help in CLI
  cli.py
Labels: documentation, enhancement, python

#90 Bump version: 0.1.4 → 0.1.5
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#97 [NO-TICKET] Adds github action to autoupdate pre-commit
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
Labels: dependencies, enhancement, github_actions, python

#99 Auto-update pre-commit hooks
  .pre-commit-config.yaml
Labels: dependencies

#107 [NO-TICKET] adds visual identifier for draft PRs
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  reviews/config.py
  reviews/controller.py
  reviews/datasource/models.py
  reviews/layout/helpers.py
  reviews/tasks.py
  setup.py
  tests/datasource/test_client.py
Labels: enhancement, python

#109 [NO-TICKET] Removes local database
  README.md
  cli.py
  create.py
  reviews/controller.py
  reviews/datasource/__init__.py
  reviews/datasource/adapters/__init__.py
  reviews/datasource/client.py
  reviews/datasource/managers/__init__.py
  reviews/datasource/managers/pull_requests.py
  reviews/layout/helpers.py
  reviews/layout/managers.py
  reviews/source_control/__init__.py
  reviews/source_control/models.py
  reviews/tasks.py
  tests/conftest.py
  tests/datasource/__init__.py
  tests/datasource/test_client.py
Labels: python

#110 Bump version: 0.1.5 → 0.1.6
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#116 [NO-TICKET] updates demo playback video to use 0.1.6
  README.md
Labels: documentation, enhancement

#117 Auto-update pre-commit hooks
  .pre-commit-config.yaml
Labels: dependencies

#114 [FEATURE-113] Refactor PR render logic into testable functions
  reviews/layout/helpers.py
  reviews/source_control/models.py
  tests/source_control/models/__init__.py
  tests/source_control/models/test_pull_request.py
Labels: python, refactor

#123 [FEATURE-122] Adds inline diff counts for pull requests
  reviews/controller.py
  reviews/layout/helpers.py
  reviews/source_control/models.py
Labels: enhancement, python

#121 [FEATURE-119] Adds support for Github Enterprise
  README.md
  reviews/config.py
  reviews/source_control/client.py
Labels: enhancement, python

#125 [FEATURE-79] Identify pull requests created by the author
  reviews/controller.py
  reviews/source_control/models.py
Labels: enhancement, python, refactor

#126 Bump version: 0.1.6 → 0.1.7
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#133 Bump version: 0.1.7 → 0.1.8
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#135 adds bandit and vulture to pre-commit
  .pre-commit-config.yaml
  Makefile
  cli-runner.py
  docker-compose.yml
  requirements_dev.txt
  reviews/__main__.py
  tests/source_control/models/test_pull_request.py
Labels: python

#138 [FEATURE-102] adds config command
  README.md
  reviews/cli/main.py
  reviews/config/__init__.py
  reviews/config/render.py
  reviews/config/settings.py
  reviews/tasks.py
  tests/test_config.py
Labels: enhancement, python

#141 Bump version: 0.1.8 → 0.1.9
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#143 [FEATURE-115] adds PATH_TO_CONFIG env var to provide configuration outside of module/repository
  README.md
  reviews/config/__init__.py
  reviews/config/settings.py
  reviews/tasks.py
Labels: enhancement, python

#144 [NO-TICKET] updates project description and classifiers
  setup.py
Labels: documentation

#145 [NO-TICKET] removes unused code and refactors tasks and config helpers
  reviews/cli/main.py
  reviews/commands.py
  reviews/config/__init__.py
  reviews/config/helpers.py
  reviews/config/settings.py
  reviews/datasource/models.py
  reviews/layout/helpers.py
Labels: python, refactor

#147 Bump version: 0.1.9 → 0.1.10
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release

#153 Bump version: 0.1.10 → 0.1.11
  .bumpversion.cfg
  reviews/version.py
  setup.py
Labels: release
